version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:
    executor:
      name: android/android-machine
    
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process"
      
    steps:
      - checkout

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleDebug
workflows:
  sample:
    jobs:
      - build-and-test
